export type Track = {
  id: string;
  title: string;
  artist: string;
  year: number;
  movie?: string;
  act: "early-love" | "longing" | "heartbreak";
};

/**
 * PEHLA PYAAR — 2010–2017
 *
 * Three-act journey:
 *
 * ACT I   → Early Love
 *          Crushes, first messages, butterflies, school romance.
 *
 * ACT II  → Longing
 *          Distance, confusion, one-sided love, "kya woh bhi mujhe..."
 *
 * ACT III → Heartbreak
 *          Memories, separation, acceptance, moving on.
 *
 * YouTube IDs:
 * - Existing IDs from the original project are preserved.
 * - Verified IDs are included where available.
 * - Empty IDs ("") should be resolved through the YouTube Music API.
 */

export const TRACKS: Track[] = [
  // ============================================================
  // ACT I — EARLY LOVE
  // ============================================================

  // 2010
    // ============================================================
  // MORE 2010 — EARLY LOVE / NOSTALGIA
  // ============================================================


  

  {
    id: "XvUSsh3gdO4",
    title: "Tujhko Jo Paaya",
    artist: "Mohit Chauhan",
    year: 2010,
    movie: "Crook",
    act: "early-love",
  },
  {
    id: "W_4xcoJCaT8",
    title: "Aadha Ishq",
    artist: "Shreya Ghoshal, Natalie Di Luccio",
    year: 2010,
    movie: "Band Baaja Baaraat",
    act: "early-love",
  },
  {
    id: "Ou3C8HcPgHw",
    title: "Ainvayi Ainvayi",
    artist: "Salim Merchant, Sunidhi Chauhan",
    year: 2010,
    movie: "Band Baaja Baaraat",
    act: "early-love",
  },
  {
    id: "QWaXpiQwtpI",
    title: "Tere Mast Mast Do Nain",
    artist: "Rahat Fateh Ali Khan",
    year: 2010,
    movie: "Dabangg",
    act: "early-love",
  },

  // ============================================================
  // MORE 2011 — ROCKSTAR / FIRST LOVE
  // ============================================================

  {
    id: "xZAXVM1rSbk",
    title: "Khaabon Ke Parinday",
    artist: "Mohit Chauhan, Alyssa Mendonsa",
    year: 2011,
    movie: "Zindagi Na Milegi Dobara",
    act: "early-love",
  },
  {
    id: "l7rLw6JJhu8",
    title: "Ishq Di Galiyan",
    artist: "Rahat Fateh Ali Khan",
    year: 2011,
    movie: "No One Killed Jessica",
    act: "early-love",
  },
  {
    id: "gkCKTuR-ECI",
    title: "Tum Ho",
    artist: "Mohit Chauhan, Suzanne D'Mello",
    year: 2011,
    movie: "Rockstar",
    act: "early-love",
  },
  {
    id: "Tw8iApinXoU",
    title: "Aur Ho",
    artist: "Mohit Chauhan, Alma Ferovic",
    year: 2011,
    movie: "Rockstar",
    act: "longing",
  },
  {
    id: "T94PHkuydcw",
    title: "Kun Faya Kun",
    artist: "A.R. Rahman, Javed Ali, Mohit Chauhan",
    year: 2011,
    movie: "Rockstar",
    act: "longing",
  },
  {
    id: "6MgsHSAcI9k",
    title: "Nadaan Parindey",
    artist: "A.R. Rahman, Mohit Chauhan",
    year: 2011,
    movie: "Rockstar",
    act: "heartbreak",
  },
  {
    id: "-3gQ6HIkRys",
    title: "Phir Se Ud Chala",
    artist: "Mohit Chauhan",
    year: 2011,
    movie: "Rockstar",
    act: "longing",
  },

  // ============================================================
  // MORE 2012 — COCKTAIL / ISHAQZAADE / JTHJ
  // ============================================================

  {
    id: "vEe-UgJvUHE",
    title: "Raabta",
    artist: "Arijit Singh",
    year: 2012,
    movie: "Agent Vinod",
    act: "early-love",
  },
  {
    id: "dSOw41qlHgU",
    title: "Pee Pa Ke",
    artist: "Neeraj Shridhar, Master Saleem",
    year: 2012,
    movie: "Chaalis Chauraasi",
    act: "early-love",
  },
  {
    id: "ZyCazQV9hls",
    title: "Tum Se Hi",
    artist: "Mohit Chauhan",
    year: 2012,
    movie: "Cocktail",
    act: "early-love",
  },
  {
    id: "IfZF7JeFrc4",
    title: "Daaru Desi",
    artist: "Benny Dayal, Shalmali Kholgade",
    year: 2012,
    movie: "Cocktail",
    act: "early-love",
  },
  {
    id: "tPGKswBLGoM",
    title: "Saans Mein Teri",
    artist: "Shafqat Amanat Ali",
    year: 2012,
    movie: "Jab Tak Hai Jaan",
    act: "longing",
  },
  {
    id: "IVk7uq6c56w",
    title: "Heer",
    artist: "Harshdeep Kaur",
    year: 2012,
    movie: "Jab Tak Hai Jaan",
    act: "heartbreak",
  },
  {
    id: "Q4TjIw1ff8A",
    title: "Ishaqzaade",
    artist: "Javed Ali, Shreya Ghoshal",
    year: 2012,
    movie: "Ishaqzaade",
    act: "early-love",
  },
  {
    id: "Q527ed5FnW8",
    title: "Pareshaan",
    artist: "Shalmali Kholgade",
    year: 2012,
    movie: "Ishaqzaade",
    act: "early-love",
  },

  // ============================================================
  // MORE 2013 — LOOTERA / RAM-LEELA / RAANJHANAA
  // ============================================================

  {
    id: "Cw6icm3-mvA",
    title: "Sawaar Loon",
    artist: "Monali Thakur",
    year: 2013,
    movie: "Lootera",
    act: "early-love",
  },
  {
    id: "DZZwwQFV4PE",
    title: "Zinda Hoon Yaar",
    artist: "Amit Trivedi",
    year: 2013,
    movie: "Lootera",
    act: "longing",
  },
  {
    id: "99NUJ1cLbBI",
    title: "Monta Re",
    artist: "Swanand Kirkire, Amit Trivedi",
    year: 2013,
    movie: "Lootera",
    act: "longing",
  },
  {
    id: "3C6mx8eebn0",
    title: "Mann Kasturi Re",
    artist: "Amit Trivedi",
    year: 2013,
    movie: "Masaan",
    act: "longing",
  },
  {
    id: "telF6KWeN48",
    title: "Lahu Munh Lag Gaya",
    artist: "Shail Hada",
    year: 2013,
    movie: "Goliyon Ki Raasleela Ram-Leela",
    act: "early-love",
  },
  {
    id: "PycY_BqbWaw",
    title: "Laal Ishq",
    artist: "Arijit Singh",
    year: 2013,
    movie: "Goliyon Ki Raasleela Ram-Leela",
    act: "heartbreak",
  },
  {
    id: "3X7x4Ye-tqo",
    title: "Nagada Sang Dhol",
    artist: "Shreya Ghoshal, Osman Mir",
    year: 2013,
    movie: "Goliyon Ki Raasleela Ram-Leela",
    act: "early-love",
  },
  {
    id: "AGsn2ycFRqI",
    title: "Tum Tak",
    artist: "Javed Ali, Kirti Sagathia, Pooja AV",
    year: 2013,
    movie: "Raanjhanaa",
    act: "early-love",
  },
  {
    id: "LU29lSULUsk",
    title: "Banarasiya",
    artist: "Shreya Ghoshal",
    year: 2013,
    movie: "Raanjhanaa",
    act: "early-love",
  },
  {
    id: "QlHeJ7cWD38",
    title: "Piya Milenge",
    artist: "Sukhwinder Singh, K.M.M.C.",
    year: 2013,
    movie: "Raanjhanaa",
    act: "longing",
  },
  {
    id: "gAXAuTc0qZM",
    title: "Aise Na Dekho",
    artist: "A.R. Rahman",
    year: 2013,
    movie: "Raanjhanaa",
    act: "early-love",
  },

  // ============================================================
  // MORE 2014 — HASEE TOH PHASEE / QUEEN / HIGHWAY
  // ============================================================

  {
    id: "qug-H-sLd04",
    title: "Zehnaseeb",
    artist: "Chinmayi, Shekhar Ravjiani",
    year: 2014,
    movie: "Hasee Toh Phasee",
    act: "early-love",
  },
  {
    id: "3H9F-RRiGcc",
    title: "Ishq Bulaava",
    artist: "Sanam Puri, Shipra Goyal",
    year: 2014,
    movie: "Hasee Toh Phasee",
    act: "early-love",
  },
  {
    id: "Er5QQzYR3iE",
    title: "Punjabi Wedding Song",
    artist: "Sunidhi Chauhan, Benny Dayal",
    year: 2014,
    movie: "Hasee Toh Phasee",
    act: "early-love",
  },
  {
    id: "cprez2G15LI",
    title: "Patakha Guddi",
    artist: "Nooran Sisters",
    year: 2014,
    movie: "Highway",
    act: "early-love",
  },
  {
    id: "S1aQhVUy_9g",
    title: "Maahi Ve",
    artist: "A.R. Rahman",
    year: 2014,
    movie: "Highway",
    act: "longing",
  },
  {
    id: "9B8Sc10hawo",
    title: "Kahaan Hoon Main",
    artist: "Jonita Gandhi",
    year: 2014,
    movie: "Highway",
    act: "longing",
  },

  // ============================================================
  // MORE 2015 — BAJIRAO / PIKU / PREM RATAN
  // ============================================================

  {
    id: "c7xOVwZ_JpE",
    title: "Deewani Mastani",
    artist: "Shreya Ghoshal, Ganesh Chandanshive",
    year: 2015,
    movie: "Bajirao Mastani",
    act: "early-love",
  },
  {
    id: "GjvAqRj6dHk",
    title: "Mohe Rang Do Laal",
    artist: "Shreya Ghoshal",
    year: 2015,
    movie: "Bajirao Mastani",
    act: "early-love",
  },
  {
    id: "4Ygz2a54i1w",
    title: "Aayat",
    artist: "Arijit Singh",
    year: 2015,
    movie: "Bajirao Mastani",
    act: "longing",
  },
  {
    id: "KMuOUIfFOPw",
    title: "Pinga",
    artist: "Shreya Ghoshal, Vaishali Made",
    year: 2015,
    movie: "Bajirao Mastani",
    act: "early-love",
  },
  {
    id: "oZ7PnR_ZKRE",
    title: "Journey Song",
    artist: "Anupam Roy, Shreya Ghoshal",
    year: 2015,
    movie: "Piku",
    act: "early-love",
  },
  {
    id: "-LWNpiWL9-s",
    title: "Bezubaan",
    artist: "Anupam Roy",
    year: 2015,
    movie: "Piku",
    act: "longing",
  },
  {
    id: "cf2E-FRCDlc",
    title: "Prem Ratan Dhan Payo",
    artist: "Palak Muchhal",
    year: 2015,
    movie: "Prem Ratan Dhan Payo",
    act: "early-love",
  },

  // ============================================================
  // MORE 2016 — FITOOR / RUSTOM / UDTA PUNJAB
  // ============================================================

  {
    id: "v4KCuphhFYw",
    title: "Tere Liye",
    artist: "Sunidhi Chauhan, Jubin Nautiyal",
    year: 2016,
    movie: "Fitoor",
    act: "longing",
  },
  {
    id: "hoXSrE3K7yw",
    title: "Haminastu",
    artist: "Zeb Bangash",
    year: 2016,
    movie: "Fitoor",
    act: "longing",
  },
  {
    id: "bq6LJ6FtmR0",
    title: "Ranga Re",
    artist: "Sunidhi Chauhan, Amit Trivedi",
    year: 2016,
    movie: "Fitoor",
    act: "heartbreak",
  },
  {
    id: "Xnn5MHkYqCY",
    title: "Tu Hi Hai",
    artist: "Raghu Dixit",
    year: 2016,
    movie: "Dear Zindagi",
    act: "early-love",
  },
  {
    id: "rwn0Zs7ELzc",
    title: "Love You Zindagi",
    artist: "Amit Trivedi, Jasleen Royal",
    year: 2016,
    movie: "Dear Zindagi",
    act: "early-love",
  },
  {
    id: "qSewQ6Nx6Bo",
    title: "Just Go to Hell Dil",
    artist: "Sunidhi Chauhan",
    year: 2016,
    movie: "Dear Zindagi",
    act: "heartbreak",
  },

  // ============================================================
  // MORE 2017 — JHMS / HALF GIRLFRIEND / BAREILLY KI BARFI
  // ============================================================

  {
    id: "vIUp4CzOrpQ",
    title: "Humsafar",
    artist: "Akhil Sachdeva",
    year: 2017,
    movie: "Badrinath Ki Dulhania",
    act: "early-love",
  },
  {
    id: "10cOJl1v4J8",
    title: "Roke Na Ruke Naina",
    artist: "Arijit Singh",
    year: 2017,
    movie: "Badrinath Ki Dulhania",
    act: "longing",
  },
  {
    id: "T9vvkSFOXpQ",
    title: "Bawara Mann",
    artist: "Jubin Nautiyal, Neeti Mohan",
    year: 2017,
    movie: "Jolly LLB 2",
    act: "early-love",
  },
  {
    id: "u8P9hAvqp6Y",
    title: "Afeemi",
    artist: "Jubin Nautiyal, Shashaa Tirupati",
    year: 2017,
    movie: "Meri Pyaari Bindu",
    act: "early-love",
  },
  {
    id: "k4R39ofX-CQ",
    title: "Maana Ke Hum Yaar Nahin",
    artist: "Parineeti Chopra",
    year: 2017,
    movie: "Meri Pyaari Bindu",
    act: "longing",
  },
  {
    id: "aGKWjgWaIX4",
    title: "Khol De Baahein",
    artist: "Monali Thakur",
    year: 2017,
    movie: "Meri Pyaari Bindu",
    act: "early-love",
  },
  {
    id: "Qn_7vrUpHj0",
    title: "Safar",
    artist: "Arijit Singh",
    year: 2017,
    movie: "Jab Harry Met Sejal",
    act: "longing",
  },
  {
    id: "HJf0UTvLoWE",
    title: "Parinda",
    artist: "Pritam, Shail Hada",
    year: 2017,
    movie: "Jab Harry Met Sejal",
    act: "longing",
  },
  {
    id: "YQZMG-4gcdQ",
    title: "Hawayein",
    artist: "Arijit Singh",
    year: 2017,
    movie: "Jab Harry Met Sejal",
    act: "heartbreak",
  },
  {
    id: "rsb-GSK2ibI",
    title: "Main Tera Boyfriend",
    artist: "Arijit Singh, Neha Kakkar",
    year: 2017,
    movie: "Raabta",
    act: "early-love",
  },
  {
    id: "vZO8Io6K00o",
    title: "Ik Vaari Aa",
    artist: "Arijit Singh",
    year: 2017,
    movie: "Raabta",
    act: "longing",
  },
  {
    id: "Hff7s8jYD10",
    title: "Lambiyaan Si Judaiyaan",
    artist: "Arijit Singh",
    year: 2017,
    movie: "Raabta",
    act: "heartbreak",
  },
  {
    id: "WCTro3qabjE",
    title: "Pee Loon",
    artist: "Mohit Chauhan",
    year: 2010,
    movie: "Once Upon a Time in Mumbaai",
    act: "early-love",
  },
  {
    id: "tPGKswBLGoM",
    title: "Bin Tere",
    artist: "Shafqat Amanat Ali, Sunidhi Chauhan",
    year: 2010,
    movie: "I Hate Luv Storys",
    act: "early-love",
  },
  {
    id: "k6a0ksWo1X4",
    title: "Bahara",
    artist: "Shreya Ghoshal",
    year: 2010,
    movie: "I Hate Luv Storys",
    act: "early-love",
  },
  {
    id: "UdE_yPU9218",
    title: "Sadka",
    artist: "Suraj Jagan, Mahalakshmi Iyer",
    year: 2010,
    movie: "I Hate Luv Storys",
    act: "early-love",
  },
  {
    id: "yIrU21hoHys",
    title: "Tere Bin",
    artist: "Atif Aslam",
    year: 2010,
    movie: "Dil Toh Baccha Hai Ji",
    act: "early-love",
  },

  // 2011
  {
    id: "O9U-KO90tnc",
    title: "Saibo",
    artist: "Shreya Ghoshal, Tochi Raina",
    year: 2011,
    movie: "Shor in the City",
    act: "early-love",
  },
  {
    id: "fj9gVmBEJFk",
    title: "I Love You",
    artist: "Ash King, Clinton Cerejo",
    year: 2011,
    movie: "Bodyguard",
    act: "early-love",
  },
  {
    id: "qYtK0JP3Q64",
    title: "Ishq Sufiyana",
    artist: "Kamal Khan",
    year: 2011,
    movie: "The Dirty Picture",
    act: "early-love",
  },
  {
    id: "ERiB-3wZaNw",
    title: "Teri Meri",
    artist: "Rahat Fateh Ali Khan, Shreya Ghoshal",
    year: 2011,
    movie: "Bodyguard",
    act: "early-love",
  },
  {
    id: "GzO2AeOm9mk",
    title: "O Saathi Re",
    artist: "Shreya Ghoshal, Vishal Dadlani",
    year: 2011,
    movie: "Shor in the City",
    act: "early-love",
  },

  // 2012
  {
    id: "OuNGySNJjWg",
    title: "Aashiyan",
    artist: "Shreya Ghoshal, Nikhil Paul George",
    year: 2012,
    movie: "Barfi!",
    act: "early-love",
  },
  {
    id: "Z93rAu25KqI",
    title: "Phir Le Aaya Dil",
    artist: "Arijit Singh",
    year: 2012,
    movie: "Barfi!",
    act: "early-love",
  },
  {
    id: "1GLgFSn6ZAA",
    title: "Saawali Si Raat",
    artist: "Arijit Singh",
    year: 2012,
    movie: "Barfi!",
    act: "early-love",
  },
  {
    id: "N2cPyl83tkQ",
    title: "Ishq Wala Love",
    artist: "Salim Merchant, Neeti Mohan, Shekhar Ravjiani",
    year: 2012,
    movie: "Student of the Year",
    act: "early-love",
  },
  {
    id: "IXk1BQZ_rww",
    title: "Mashallah",
    artist: "Wajid, Shreya Ghoshal",
    year: 2012,
    movie: "Ek Tha Tiger",
    act: "early-love",
  },
  {
    id: "eaRm4KAZfIM",
    title: "Tum Hi Ho Bandhu",
    artist: "Neeraj Shridhar, Kavita Seth",
    year: 2012,
    movie: "Cocktail",
    act: "early-love",
  },
  {
    id: "mfNnCKMx-tk",
    title: "Tu Hi Mera",
    artist: "Shafqat Amanat Ali",
    year: 2012,
    movie: "Jannat 2",
    act: "early-love",
  },

  // 2013 — Aashiqui 2 era
  {
    id: "IJq0yyWug1k",
    title: "Tum Hi Ho",
    artist: "Arijit Singh",
    year: 2013,
    movie: "Aashiqui 2",
    act: "early-love",
  },
  {
    id: "NPC-9hYbkLE",
    title: "Chahun Main Ya Naa",
    artist: "Arijit Singh, Palak Muchhal",
    year: 2013,
    movie: "Aashiqui 2",
    act: "early-love",
  },
  {
    id: "1If9aw74Tj4",
    title: "Sunn Raha Hai",
    artist: "Ankit Tiwari",
    year: 2013,
    movie: "Aashiqui 2",
    act: "early-love",
  },
  {
    id: "2bMEe0UYa8E",
    title: "Piya Aaye Na",
    artist: "KK, Tulsi Kumar",
    year: 2013,
    movie: "Aashiqui 2",
    act: "early-love",
  },
  {
    id: "cAX_nMkunAM",
    title: "Hum Mar Jayenge",
    artist: "Arijit Singh, Tulsi Kumar",
    year: 2013,
    movie: "Aashiqui 2",
    act: "early-love",
  },
  {
    id: "BIFbGlWfc6U",
    title: "Bhula Dena",
    artist: "Mustafa Zahid",
    year: 2013,
    movie: "Aashiqui 2",
    act: "early-love",
  },
  {
    id: "O1BG_5Pk5Bg",
    title: "Milne Mujhse Aayi",
    artist: "Arijit Singh",
    year: 2013,
    movie: "Aashiqui 2",
    act: "early-love",
  },
  {
    id: "vrlL7iyQ2SA",
    title: "Aasan Nahin Yahan",
    artist: "Arijit Singh",
    year: 2013,
    movie: "Aashiqui 2",
    act: "longing",
  },
  {
    id: "YipYZY3mmO0",
    title: "Meri Aashiqui",
    artist: "Arijit Singh, Palak Muchhal",
    year: 2013,
    movie: "Aashiqui 2",
    act: "early-love",
  },

  // Other 2013
  {
    id: "fdubeMFwuGs",
    title: "Ilahi",
    artist: "Arijit Singh",
    year: 2013,
    movie: "Yeh Jawaani Hai Deewani",
    act: "early-love",
  },
  {
    id: "jHNNMj5bNQw",
    title: "Kabira",
    artist: "Tochi Raina, Rekha Bhardwaj",
    year: 2013,
    movie: "Yeh Jawaani Hai Deewani",
    act: "longing",
  },
  {
    id: "qH1eRWlJpsY",
    title: "Kabhi Jo Baadal Barse",
    artist: "Arijit Singh",
    year: 2013,
    movie: "Jackpot",
    act: "early-love",
  },
  {
    id: "aKdqQ5BC_S4",
    title: "Main Rang Sharbaton Ka",
    artist: "Atif Aslam, Chinmayi",
    year: 2013,
    movie: "Phata Poster Nikhla Hero",
    act: "early-love",
  },
  {
    id: "2PMWLyB4WYo",
    title: "Tera Rastaa Main Chhodun Na",
    artist: "Arijit Singh, Shilpa Rao",
    year: 2013,
    movie: "Chennai Express",
    act: "early-love",
  },
  {
    id: "zvHapBaPW60",
    title: "Saans",
    artist: "Shreya Ghoshal, Mohit Chauhan",
    year: 2013,
    movie: "Jab Tak Hai Jaan",
    act: "early-love",
  },
  {
    id: "qpIdoaaPa6U",
    title: "Jeene Laga Hoon",
    artist: "Atif Aslam, Shreya Ghoshal",
    year: 2013,
    movie: "Ramaiya Vastavaiya",
    act: "early-love",
  },

  // ============================================================
  // ACT II — LONGING
  // ============================================================

  // 2014
  {
    id: "H2f7MZaw3Yo",
    title: "Samjhawan",
    artist: "Arijit Singh, Shreya Ghoshal",
    year: 2014,
    movie: "Humpty Sharma Ki Dulhania",
    act: "longing",
  },
  {
    id: "9FXm9R2VTBg",
    title: "Galliyan",
    artist: "Ankit Tiwari",
    year: 2014,
    movie: "Ek Villain",
    act: "longing",
  },
  {
    id: "7tElHNHLSKY",
    title: "Humdard",
    artist: "Arijit Singh",
    year: 2014,
    movie: "Ek Villain",
    act: "longing",
  },
  {
    id: "0ktkARZy4rw",
    title: "Zaroorat",
    artist: "Mustafa Zahid",
    year: 2014,
    movie: "Ek Villain",
    act: "longing",
  },
  {
    id: "SkzjBUvRTQk",
    title: "Awari",
    artist: "Soch",
    year: 2014,
    movie: "Ek Villain",
    act: "longing",
  },
  {
    id: "lVpZaByCWUE",
    title: "Mast Magan",
    artist: "Arijit Singh, Chinmayi",
    year: 2014,
    movie: "2 States",
    act: "early-love",
  },
  {
    id: "bIV9kE9JPJg",
    title: "Offo",
    artist: "Aditi Singh Sharma, Amitabh Bhattacharya",
    year: 2014,
    movie: "2 States",
    act: "early-love",
  },
  {
    id: "2ltGXfmI6mk",
    title: "Muskurane",
    artist: "Arijit Singh",
    year: 2014,
    movie: "CityLights",
    act: "early-love",
  },
  {
    id: "hK_Sey44PkU",
    title: "Manwa Laage",
    artist: "Shreya Ghoshal, Arijit Singh",
    year: 2014,
    movie: "Happy New Year",
    act: "early-love",
  },
  {
    id: "rFFq9_52IjI",
    title: "Suno Na Sangemarmar",
    artist: "Arijit Singh",
    year: 2014,
    movie: "Youngistaan",
    act: "early-love",
  },
  {
    id: "cSALq5b2Qhg",
    title: "Meherbaan",
    artist: "Ash King, Shilpa Rao, Shekhar Ravjiani",
    year: 2014,
    movie: "Bang Bang!",
    act: "early-love",
  },

  // 2015
  {
    id: "GYFDRoJtfGM",
    title: "Bolna",
    artist: "Arijit Singh, Asees Kaur",
    year: 2015,
    movie: "Kapoor & Sons",
    act: "early-love",
  },
  {
    id: "FOkVXadnO88",
    title: "Hasi Ban Gaye",
    artist: "Ami Mishra",
    year: 2015,
    movie: "Hamari Adhuri Kahani",
    act: "longing",
  },
  {
    id: "IgYF-LjU-MI",
    title: "Hamari Adhuri Kahani",
    artist: "Arijit Singh",
    year: 2015,
    movie: "Hamari Adhuri Kahani",
    act: "longing",
  },
  {
    id: "_LRr9aliWMs",
    title: "Hasi",
    artist: "Ami Mishra",
    year: 2015,
    movie: "Hamari Adhuri Kahani",
    act: "longing",
  },
  {
    id: "9wXug003YgM",
    title: "Humnava",
    artist: "Arijit Singh",
    year: 2015,
    movie: "Hamari Adhuri Kahani",
    act: "longing",
  },
  {
    id: "sK7riqg2mr4",
    title: "Agar Tum Saath Ho",
    artist: "Alka Yagnik, Arijit Singh",
    year: 2015,
    movie: "Tamasha",
    act: "longing",
  },
  {
    id: "TpMSsbzvRe4",
    title: "Matargashti",
    artist: "Mohit Chauhan",
    year: 2015,
    movie: "Tamasha",
    act: "early-love",
  },
  {
    id: "-0lql0pSSwQ",
    title: "Tu Koi Aur Hai",
    artist: "A.R. Rahman",
    year: 2015,
    movie: "Tamasha",
    act: "longing",
  },
  {
    id: "EB9ugJ4ICgU",
    title: "Wat Wat Wat",
    artist: "Arijit Singh, Shashwat Singh",
    year: 2015,
    movie: "Tamasha",
    act: "early-love",
  },
  {
    id: "sOhESxhibAM",
    title: "Safarnama",
    artist: "Lucky Ali",
    year: 2015,
    movie: "Tamasha",
    act: "longing",
  },
  {
    id: "kv_5z2ROptE",
    title: "Tu Chahiye",
    artist: "Atif Aslam",
    year: 2015,
    movie: "Bajrangi Bhaijaan",
    act: "early-love",
  },
  {
    id: "DmKSGL8kucM",
    title: "Zindagi Kuch Toh Bata",
    artist: "Jubin Nautiyal",
    year: 2015,
    movie: "Bajrangi Bhaijaan",
    act: "longing",
  },
  {
    id: "AEIVhBS6baE",
    title: "Gerua",
    artist: "Arijit Singh, Antara Mitra",
    year: 2015,
    movie: "Dilwale",
    act: "early-love",
  },
  {
    id: "MK5Pqk5czuI",
    title: "Janam Janam",
    artist: "Arijit Singh, Antara Mitra",
    year: 2015,
    movie: "Dilwale",
    act: "early-love",
  },
  {
    id: "59esPpakrGs",
    title: "Daayre",
    artist: "Arijit Singh",
    year: 2015,
    movie: "Dilwale",
    act: "longing",
  },

  // ============================================================
  // ACT III — HEARTBREAK
  // ============================================================

  // 2016 — SANAM RE
  {
    id: "DS-raAyMxl4",
    title: "Sanam Re",
    artist: "Mithoon, Arijit Singh",
    year: 2016,
    movie: "Sanam Re",
    act: "heartbreak",
  },
  {
    id: "d00mhGDmEPs",
    title: "Gazab Ka Hain Yeh Din",
    artist: "Arijit Singh, Amaal Mallik",
    year: 2016,
    movie: "Sanam Re",
    act: "early-love",
  },
  {
    id: "vL3_GMhNe4M",
    title: "Hua Hain Aaj Pehli Baar",
    artist: "Amaal Mallik, Armaan Malik, Palak Muchhal",
    year: 2016,
    movie: "Sanam Re",
    act: "early-love",
  },
  {
    id: "1V6nAuqz7WM",
    title: "Humne Pee Rakhi Hai",
    artist: "Jaz Dhami, Neha Kakkar, Ikka",
    year: 2016,
    movie: "Sanam Re",
    act: "early-love",
  },
  {
    id: "Q3ghTIi1ZwQ",
    title: "Kya Tujhe Ab Ye Dil Bataye",
    artist: "Falak Shabbir",
    year: 2016,
    movie: "Sanam Re",
    act: "longing",
  },
  {
    id: "P5ybGFWTbPk",
    title: "Tere Liye",
    artist: "Mithoon, Ankit Tiwari",
    year: 2016,
    movie: "Sanam Re",
    act: "longing",
  },
  {
    id: "94tY8gVK4xM",
    title: "Tum Bin",
    artist: "Shreya Ghoshal",
    year: 2016,
    movie: "Sanam Re",
    act: "heartbreak",
  },
  {
    id: "Jd8XIlEfz7c",
    title: "Chhote Chhote Tamashe",
    artist: "Shaan",
    year: 2016,
    movie: "Sanam Re",
    act: "early-love",
  },

  // 2016 — OTHER HEARTBREAK
  {
    id: "284Ov7ysmfA",
    title: "Channa Mereya",
    artist: "Arijit Singh",
    year: 2016,
    movie: "Ae Dil Hai Mushkil",
    act: "heartbreak",
  },
  {
    id: "dXKrpx6cZQg",
    title: "Ae Dil Hai Mushkil",
    artist: "Arijit Singh",
    year: 2016,
    movie: "Ae Dil Hai Mushkil",
    act: "heartbreak",
  },
  {
    id: "vrqFJ-yjkRw",
    title: "Bulleya",
    artist: "Amit Mishra, Shilpa Rao",
    year: 2016,
    movie: "Ae Dil Hai Mushkil",
    act: "heartbreak",
  },
  {
    id: "t-zwwOBHQlo",
    title: "Hoor",
    artist: "Atif Aslam",
    year: 2016,
    movie: "Hindi Medium",
    act: "longing",
  },
  {
    id: "f9_C8J4gqzQ",
    title: "Bol Do Na Zara",
    artist: "Armaan Malik",
    year: 2016,
    movie: "Azhar",
    act: "early-love",
  },
  {
    id: "NzijbnP6B0w",
    title: "Dekha Hazaro Dafaa",
    artist: "Arijit Singh, Palak Muchhal",
    year: 2016,
    movie: "Rustom",
    act: "early-love",
  },
  {
    id: "wQ8cfdBzaHI",
    title: "Lo Maan Liya",
    artist: "Arijit Singh",
    year: 2016,
    movie: "Raaz Reboot",
    act: "heartbreak",
  },
  {
    id: "rfiaZ-PX01o",
    title: "Sanam Teri Kasam",
    artist: "Ankit Tiwari, Palak Muchhal",
    year: 2016,
    movie: "Sanam Teri Kasam",
    act: "heartbreak",
  },
  {
    id: "pAMksXUJjGs",
    title: "Ikk Kudi",
    artist: "Shahid Mallya",
    year: 2016,
    movie: "Udta Punjab",
    act: "longing",
  },
  {
    id: "SVbfl6DilTY",
    title: "Jag Ghoomeya",
    artist: "Rahat Fateh Ali Khan",
    year: 2016,
    movie: "Sultan",
    act: "longing",
  },
  {
    id: "Ov0YGGSY6gY",
    title: "Kaun Tujhe",
    artist: "Palak Muchhal",
    year: 2016,
    movie: "M.S. Dhoni: The Untold Story",
    act: "heartbreak",
  },
  {
    id: "J6PoLcHlrzg",
    title: "Jab Tak",
    artist: "Armaan Malik",
    year: 2016,
    movie: "M.S. Dhoni: The Untold Story",
    act: "longing",
  },
  {
    id: "5mpq_4rzB1U",
    title: "Tere Sang Yaara",
    artist: "Atif Aslam",
    year: 2016,
    movie: "Rustom",
    act: "early-love",
  },

  // 2017
  {
    id: "YQZMG-4gcdQ",
    title: "Hawayein",
    artist: "Arijit Singh",
    year: 2017,
    movie: "Jab Harry Met Sejal",
    act: "longing",
  },
  {
    id: "_iktURk0X-A",
    title: "Phir Bhi Tumko Chaahunga",
    artist: "Arijit Singh, Shashaa Tirupati",
    year: 2017,
    movie: "Half Girlfriend",
    act: "heartbreak",
  },
  {
    id: "1gwoGQhXvAo",
    title: "Baarish",
    artist: "Ash King, Shashaa Tirupati",
    year: 2017,
    movie: "Half Girlfriend",
    act: "longing",
  },
  {
    id: "mpMNPifZTUo",
    title: "Thoda Aur",
    artist: "Arijit Singh, Shreya Ghoshal",
    year: 2017,
    movie: "Ranchi Diaries",
    act: "longing",
  },
  {
    id: "DK_UsATwoxI",
    title: "Nazm Nazm",
    artist: "Arko",
    year: 2017,
    movie: "Bareilly Ki Barfi",
    act: "early-love",
  },
  {
    id: "d2uHe3bTjqo",
    title: "O Saathi",
    artist: "Atif Aslam",
    year: 2017,
    movie: "Sweetiee Weds NRI",
    act: "longing",
  },
];